services:
  - type: web
    runtime: static
    name: apidocs
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: dist
    domains:
      - api.beeminder.com
    previews:
      generation: automatic
